---
abstract: unknown
author:
  - 'Mario Zieschang <mziescha@cpan.org>'
build_requires:
  DBD::SQLite: '1.4'
  DBI: '1.632'
  File::Spec: '0'
  Getopt::Long: '2.42'
  Hash::MD5: '0.05'
  JSON::Parse: '0.31'
  Method::Signatures::Simple: '1.07'
  Moose: '2.1403'
  MooseX::HasDefaults::RO: '0'
  MooseX::Types::LoadableClass: '0.013'
  MooseX::Types::Moose: '0.45'
  MooseX::Types::Path::Class: '0.06'
  MooseX::Types::PerlVersion: '0.002'
  Path::Class: '0.3'
  Pod::Coverage::TrustPod: '0'
  Pod::Usage: '0'
  Storable: '2.49'
  Test::CheckManifest: '0'
  Test::Cmd: '0'
  Test::Exception: '0'
  Test::Pod::Coverage: '0'
  Test::PostgreSQL: '1.01'
  Test::Requires: '0'
  Test::Spelling: '0'
  Text::Trim: '1.02'
  Time::Piece: '1.27'
  YAML: '1.13'
  YAML::XS: '0.55'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Schema-Changelog
no_index:
  directory:
    - t
    - inc
requires:
  DBD::SQLite: '1.4'
  DBI: '1.632'
  File::Spec: '0'
  Getopt::Long: '2.42'
  Hash::MD5: '0.05'
  JSON::Parse: '0.31'
  Method::Signatures::Simple: '1.07'
  Moose: '2.1403'
  MooseX::HasDefaults::RO: '0'
  MooseX::Types::LoadableClass: '0.013'
  MooseX::Types::Moose: '0.45'
  MooseX::Types::Path::Class: '0.06'
  MooseX::Types::PerlVersion: '0.002'
  Path::Class: '0.3'
  Pod::Coverage::TrustPod: '0'
  Pod::Usage: '0'
  Storable: '2.49'
  Test::CheckManifest: '0'
  Test::Cmd: '0'
  Test::Exception: '0'
  Test::Pod::Coverage: '0'
  Test::PostgreSQL: '1.01'
  Test::Requires: '0'
  Test::Spelling: '0'
  Text::Trim: '1.02'
  Time::Piece: '1.27'
  YAML: '1.13'
  YAML::XS: '0.55'
  perl: '5.010000'
resources:
  repository: https://github.com/mziescha/DBIx-Schema-Changelog.git
version: v0.6.1
